version: '2'
services:
    portal-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/portal/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=portal
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
